### ISSUE TITLE
starting HMM and HDP models

### ISSUE THREAD

**Issue by PengNi** [ArtRand/signalAlign#15]
Hi everyone,
when using the _trainModels_ program, how do I choose the needed HMM and HDP models as the starting models?
Or, how to use the --in_template_hmm/--in_complement_hmm, --templateHDP/--complementHDP parameters?

**Comment by PengNi** [comment]
Hi @mitenjain ,

May you help me with this issue? 

I used two _.model_ files in _/models_ folder to run the _BuildModels.py_ script in _signalAlign_notebook_ , with Ecoli CCWGG R9 data. But I didn't get the expected results showed in the paper.

The training and testing positions were splited as described in the paper. And the command I ran is like this:
```
python ../signalAlign_notebook/experiment_scripts/BuildModels.py \
-r SRP098631/ecoli_k12.fasta \
-pcr SRP098631/ecoli/08_20_16_R9_WGA_Ecoli/MJ/downloads/pass/ \
-gen SRP098631/ecoli/08_05_16_R9_gEcoli_2D/DD/downloads/pass/ \ 
-o SRP098631/trainModels_Ecoli.CCWGG.try5 \
--positions SRP098631/ecoli_ccwgg_positions/cytosine.train.positions \ 
--positions SRP098631/ecoli_ccwgg_positions/cytosine.test.positions \ 
--motif SRP098631/ecoli_ccwgg_positions/cytosine.train.target \
--motif SRP098631/ecoli_ccwgg_positions/cytosine.test.target \
-x cytosine2 -j 36 --split 0.5 -a 30000 -i 30 \
--in_template_hmm ../signalAlign/models/testModelR9_acegit_template.model \
--in_complement_hmm ../signalAlign/models/testModelR9_acegit_complement.model \ 
-n 1000000 -e 1000000 --hdp_em 1 \
1>trainModels_Ecoli.CCWGG.try5.log \
2>trainModels_Ecoli.CCWGG.try5.err
```

So for the Ecoli CCWGG data, are the _testModelR9_acegit_template.model_ and _testModelR9_acegit_complement.model_ correct? 
Or there are other parameters wrong?

Best, 
Peng

**Comment by PengNi** [comment]
@mitenjain @ArtRand , Maybe I should move the issue to the _signalAlign_notebook_ repo?

Peng

**Comment by mitenjain** [comment]
Hi @PengNi , 

That looks right. I am pinging Art so that he can confirm and send appropriate info. 

-Miten

**Comment by PengNi** [comment]
@mitenjain ,

Thank you!

More information for you to judge:
I used the ErrorRate.py to test the results, got the accuracies: 
both         0.859 (mean_coverage: 27.125), 
template  0.938 (mean_coverage: 13.584).

Best regards,
Peng

**Comment by mitenjain** [comment]
Hi @PengNi ,

I have messaged Art who will respond to your query with specific details. 

-Miten

**Comment by PengNi** [comment]
Hi Miten and @ArtRand ,

I did two more tests for this issue.

(1) I used _runSignalAlign_ with two trained models in _HDP_models_ repo (HDP_models/ecoli_r9_models/ccwgg_supervised_model/template_trained.hmm, HDP_models/ecoli_r9_models/ccwgg_supervised_model/complement_trained.hmm) to classify the same testing group in the above test, the results are:
template: 0.947 (13.598), both: 0.926 (27.103)

(2) Then I used the two trained models as the starting models of _BuildModels.py_. The command is like this:
```shell
python ../signalAlign_notebook/experiment_scripts/BuildModels.py \
-r SRP098631/ecoli_k12.fasta \
-pcr SRP098631/ecoli/08_20_16_R9_WGA_Ecoli/MJ/downloads/pass/ \
-gen SRP098631/ecoli/08_05_16_R9_gEcoli_2D/DD/downloads/pass/ \ 
-o SRP098631/trainModels_Ecoli.CCWGG.try8 \
--positions SRP098631/ecoli_ccwgg_positions/cytosine.train.positions \ 
--positions SRP098631/ecoli_ccwgg_positions/cytosine.test.positions \ 
--motif SRP098631/ecoli_ccwgg_positions/cytosine.train.target \
--motif SRP098631/ecoli_ccwgg_positions/cytosine.test.target \
-x cytosine2 -j 36 --split 0.5 -a 30000 -i 30 \
--in_template_hmm ../HDP_models/ecoli_r9_models/ccwgg_supervised_model/template_trained.hmm \
--in_complement_hmm ../HDP_models/ecoli_r9_models/ccwgg_supervised_model/complement_trained.hmm \ 
-n 1000000 -e 1000000 --hdp_em 1 \
1>trainModels_Ecoli.CCWGG.try8.log \
2>trainModels_Ecoli.CCWGG.try8.err
```
The results are:
template: 0.950 (13.642), both: 0.939 (27.206)

I know these two tests are not reasonable in some way. But I hope they can help with finding the problems.

Best,
Peng
