### ISSUE TITLE
1709 CCWGG motifs in E.coli stationary phase cells

### ISSUE THREAD

**Issue by PengNi** [ArtRand/signalAlign#16]
Hi,

Does anyone know where to find the positions of the 1,709 motifs used in the [signalAlign paper](https://www.nature.com/articles/nmeth.4189) in Nature Mehods?
I just cannot figure out how to parse these motifs from the raw data.
Thank you very much!

Peng

**Comment by PengNi** [comment]
I could not be more appreciate if you tell me. @mitenjain , @ArtRand

**Comment by mitenjain** [comment]
Hi Peng, 

Have you checked this paper: https://www.nature.com/articles/ncomms1878

This was the source of our motif positions. The call file is this, one that includes calls for both strands: https://github.com/ArtRand/CytosineMethylationAnalysis/blob/master/data/ecoli/test_sites.tsv

Hope this helps.
-Miten

**Comment by PengNi** [comment]
Thanks Miten, 

This helps a lot.

I checked the [ncomms1878 ](https://www.nature.com/articles/ncomms1878)paper. However, I'm still not sure if I can parse the same 1709 motifs from this paper as you do.

So does the [test_sites.tsv](https://github.com/ArtRand/CytosineMethylationAnalysis/blob/master/data/ecoli/test_sites.tsv) contain all the positions of the 1709 motifs mentioned in the _signalAlign_ paper? To me it seems like that the [test_sites.tsv](https://github.com/ArtRand/CytosineMethylationAnalysis/blob/master/data/ecoli/test_sites.tsv) is for the testing. If that so, could you give me the other part motifs for training? 

Many thanks.
Peng

**Comment by mitenjain** [comment]
Hi Peng,

Yes, that file should include everything I think. The test sites here is indicating sites to look at during both training and testing. There is hopefully more information in the Supp. Note 2.9 Dividing E. coli methylation motifs into training and test groups.

From the results of bisulfite sequencing performed on stationary phase E. coli K12 MG1655 we parsed 1,709 motifs, A, with the sequence CCWGG where the innermost cytosine is methylated [6] (W refers to either A or T). Analysis of the genome showed that 456 different 6-mers occur at the motifs centering around the second cytosine, let this set be denoted as K. A training group of motifs, T, was generated by randomly drawing motifs from A until all 6-mers in K were observed. Additional motifs from A were added at random until T contained roughly half of the total motifs. The remaining motifs were assigned to the test group, R, such that T ∩ R = Ø. The same groupings were used in experiments with 5-mers.

Let me know as you have any questions. 
Best regards,
Miten

**Comment by PengNi** [comment]
Hi Miten,

Thanks very much for giving me the information with the details. 

I read the Supp. Note 2.9 before, and I've done my own test. However, I still have some questions:

(1) The paper mentioned **1709** CCWGG motifs, but I only get **1708** positions (854 on each strand) from [test_sites.tsv](https://github.com/ArtRand/CytosineMethylationAnalysis/blob/master/data/ecoli/test_sites.tsv).

More, in your paper you said "We evenly divided 3,418 constitutively methylated cytosines into a training and testing set." I don't quite understand what the 3418 methylated cytosines mean. Does this mean that there are 1709 cytosines on each group data of two samples (pcrDNA, gDNA)?

(2) Supp. Note 2.9 says that there are **456** 6-mers. However, I only got **451** different 6-mers.

To get the _6-mers_, fist I extracted all _11-mers_ where the inner cytosines of the 1708 motifs are in the middle. Then I put all six _6-mers_ from every _11-mer_ together. Does this the way you did? Or this is because that I used a different ecoli genome reference? I got a K12 MG1655 genome from [ftp://ftp.ensemblgenomes.org/pub/release-29/bacteria//fasta/bacteria_0_collection/escherichia_coli_str_k_12_substr_mg1655/dna/Escherichia_coli_str_k_12_substr_mg1655.GCA_000005845.2.29.dna.genome.fa.gz](ftp://ftp.ensemblgenomes.org/pub/release-29/bacteria//fasta/bacteria_0_collection/escherichia_coli_str_k_12_substr_mg1655/dna/Escherichia_coli_str_k_12_substr_mg1655.GCA_000005845.2.29.dna.genome.fa.gz).

Thanks!

Best,
Peng

**Comment by PengNi** [comment]
Could you just tell me where I am wrong? @mitenjain 

Thanks,
Peng

**Comment by mitenjain** [comment]
Hi Peng,

I am sending a file that does have 1709 motifs. It may be that the test sites files was missing one due to a leave-one out test (I will check this with @ArtRand). Hope this is useful. 
[ecoli_all_both.txt](https://github.com/ArtRand/signalAlign/files/2280754/ecoli_all_both.txt)

This should hopefully also help with the 6mers.

-Miten

**Comment by PengNi** [comment]
Hi Miten,

With the new file, the number of motifs and 6mers match with the paper.
Thank you very much.

Best,
Peng

**Comment by PengNi** [comment]
Hi @mitenjain ,

Could you tell me which tool did you use to analyze the bisulfite sequencing data from [ncomms1878](https://www.nature.com/articles/ncomms1878)? Is the tool [Bismark](http://www.bioinformatics.babraham.ac.uk/projects/bismark/)?

Best,
Peng

**Comment by mitenjain** [comment]
Hi @PengNi, 

Yes. We used the data and analysis as described by the source paper. 

-Miten

**Comment by PengNi** [comment]
Hi @mitenjain ,

Sorry to bother you so many times.

According to the analysis in [ncomms1878](https://www.nature.com/articles/ncomms1878) paper, methylation of all (24090) CCWGG sites is nearly complete during stationary phase. I used [Bismark](http://www.bioinformatics.babraham.ac.uk/projects/bismark/) and got a similar result as in the source paper.

So what principles you used to parse the 1709 high-confidence motifs? If possible, could you tell me the parameters of [Bismark](http://www.bioinformatics.babraham.ac.uk/projects/bismark/) (and Bowtie?) when you analysis the bisulfite data, too? 

I couldn't appreciate more.

Best regards,
Peng

**Comment by mitenjain** [comment]
Hi @PengNi ,

In bisulfite data you also get the # of cytosine calls (and # of 5mC calls). If I recall correctly, that is what we used to get the high-confidence motifs, i.e. cytosines which were all called as methylated (100% with at least >5 or >10 of calls from bisulfite). For processing with Bismark and Bowtie, we used the standard parameters, making sure of the versions as recommended in the ncomms1878 paper.

Hope this is useful.
-Miten

**Comment by PengNi** [comment]
Thanks for telling me that, Miten. It is really helpful.

Best,
Peng

**Comment by PengNi** [comment]
Hi @mitenjain , @ArtRand ,

I have been trying to parse the 1709 motifs from the bisulfite data as you did. However, based the tools and the metrics you told me, I still can't get the same motifs.

Here is the result I got:
(1) I got **1,995** cytosines (in the forward strand of reference) which are 100% called as 5mC with at least **15** calls from bisulfite, but there are only **417** intersections with your 1709 cytosines.
(2) According to my result,  there are 32 cytosines (of the 1709 motifs you used) which have no reads coverage. And I cannot see the pattern you used to choose the 1709 motifs based on my result.

Here is the pipeline I ran ([FastQC](https://www.bioinformatics.babraham.ac.uk/projects/fastqc/) v0.11.7, [TrimGalore](https://www.bioinformatics.babraham.ac.uk/projects/trim_galore/) 0.5.0_dev, [Bismark](https://www.bioinformatics.babraham.ac.uk/projects/bismark/) v0.19.1, [bowtie](http://bowtie-bio.sourceforge.net/index.shtml) v1.2.2):
```shell
# based on the result of FastQC, I trimed the first 7bp of each read, 
# the last 29bp of each read are kept.
FastQC/fastqc -o ./ -f fastq bs_wildtype_stationary.fastq
TrimGalore/trim_galore --hardtrim3 29 bs_wildtype_stationary.fastq

# bismark commands
# with bismark, I got a 91.2% Mapping efficiency (3016931 of 3309564) of the reads
bismark_genome_preparation --bowtie1 --verbose ecoli_k12_gnome/

bismark --parallel 20 --bowtie1 --non_directional -n 2 \
--genome ecoli_k12_gnome/ \
bs_wildtype_stationary.29bp_3prime.fq

bismark_methylation_extractor -s --comprehensive --parallel 20 --bedGraph \
--cytosine_report --zero_based --CX --buffer_size 20G \
--genome_folder ecoli_k12_gnome/ \
bs_wildtype_stationary.29bp_3prime_bismark.bam
```

I wonder if there are some pre-processing steps I missed for the bisulfite data. Could you tell me where I am wrong, or the exact way you processing the bisulfite data?

Many thanks and Best regards,
Peng

**Comment by mitenjain** [comment]
Hi @PengNi ,

Unfortunately a lot of the files and documentation that we had parsed in 2014-15 for these data were lost during a server move last month (to conserve space). We will have to re-parse some of our own data in order to figure out whats going on. We will be in touch as we get to re-processing the bisulfite data. 

I will also try to find the correspondence that I had with the authors of the NComms E. coli paper and send you any details I find if they may be useful.

Best regards,
Miten

PS: I saw your DeepSignal bioRxiv, very cool work. Congratulations and good luck :)

**Comment by PengNi** [comment]
Hi Miten ,

That would be wonderful! I truly appreciate that.

Best,
Peng

**Comment by mitenjain** [comment]
HI @PengNi ,

I haven't yet had a chance to parse data but if you send me an email (miten@soe.ucsc.edu) I can forward you processed data from the NComms paper.

Best regards,
Miten

**Comment by ardakdemir** [comment]
Dear @mitenjain,

I am working on implementing and training my own model for methylation calling.

Thanks a lot for the above explanations and providing the datasets. I have read through the above issue and have some questions.
I obtained a dataset from the following link : 

https://sra-pub-src-1.s3.amazonaws.com/SRR5219626/puc_minion.tar.gz.1

which contains many fast5 files. How exactly should I use these fast5 files, the file called 'ecoli_all_both.txt' and a reference genome, for creating a dataset for training and testing? I assume I need raw nanopore signals, corresponding nucleotide sequence, motif position and the methylation label as inputs. Is that correct?

It seems like a bit of dirty work if I understand correctly which makes it very laborous to replicate the experiments mentioned on the paper. Is it possible for you to provide the dataset ready to use, i.e. the raw nanopore signals, methylation label, position of the metylation etc.

Thanks a lot in advance

Arda

**Comment by mitenjain** [comment]
Dear @ardakdemir,

Sorry for the hassle. It is worth noting that all of the data from the paper are outdated from chemistry, basecalling, and informatics standpoint now. It may be worth working from the human genome dataset (https://github.com/nanopore-wgs-consortium/NA12878/blob/master/Genome.md) and training your models using the new (and in the process of being updated) signalAlign repository (https://github.com/UCSC-nanopore-cgl/signalAlign). If you want the the older raw data (and information), I am happy to share and help as possible.

Best regards,
Miten

**Comment by ardakdemir** [comment]
Dear Miten,

Thanks a lot for your reply. I agree with you on that, so I prefer using
the updated dataset.

I assume the dataset you pointed out has no methylation labels, right?
Do you possess any other nanopore basecalling data with methylation labels?

Kind regards

Arda

Miten Jain <notifications@github.com>, 13 Eki 2019 Paz, 14:02 tarihinde
şunu yazdı:

**Comment by mitenjain** [comment]
Dear @ardakdemir ,

There are some public bisulfite sequencing data. For human samples they would be the place to start. We are generating and analyzing more data that could serve useful in this regard. Those should release in a few months. 

You could also collect some publicly available data (like GM12878) and basecall using Guppy with the CpG methylation model. This will generate some methylation labels that you could correlate with bisulfite data to create a set of training sites for your own model.

Does that make sense?

Best regards,
Miten

**Comment by ardakdemir** [comment]
Thanks a lot for your suggestions!

Yeah it makes sense :)

Miten Jain <notifications@github.com>, 18 Eki 2019 Cum, 01:50 tarihinde
şunu yazdı:
